---
# tasks file for roles/website
- include: nginx-install.yml
  notify: 
    - Reload NGINX

# - name: restart service
#   service:
#     name: nginx
#     state: restarted
#   become: yes

 
- include: copy-wwebserver.yml
- include: html-copy.yml
  
  notify: 
    - Reload NGINX